# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Life on Mars' do
pod 'AFNetworking', '~> 3.0'
end

target 'Life on MarsTests' do

end

target 'Life on MarsUITests' do

end

